# This YAML file contains nginx & csi cinder driver objects,
# which are necessary to run nginx with csi cinder driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cinderplugin
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  serviceName: nginx
  replicas: 4
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/www/html
              name: csi-data-cinderplugin
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: csi-data-cinderplugin
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: csi-sc-cinderplugin